spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.106:3306/logDB?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
        default-property-inclusion: non_null



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.imooc.dataobject
  ##开启驼峰映射
  configuration:
    map-underscore-to-camel-case: true

error:
  whitelabel:
    enabled:  false

server:
  servlet:
    context-path: /log